[package]
name = "RustLab290"
version = "0.1.0"
edition = "2024"
[[bin]]
name = "spreadsheet"
path = "src/main.rs"

[dependencies]
leptos = { version = "0.5", features = ["csr"] }
csv = "1.3.0"
console_log = "1"
wasm-bindgen = "0.2.92"
web-sys = "0.3.69"
js-sys = "0.3.69"
serde-wasm-bindgen = "0.6.3"
console_error_panic_hook = "0.1.7"