[package]
name = "RustLab290"
version = "0.1.0"
edition = "2024"
[[bin]]
name = "spreadsheet"
path = "src/main.rs"

[dependencies]
leptos = { version = "0.5", features = ["csr"] }
console_error_panic_hook = "0.1"
console_log = "1"
